title: Jason Fong
description: Data Science Lead
url: ""
baseurl: ""

author:
  name: Jason Fong
  image: /assets/self_photo.jpg
  email: fongjason23@gmail.com
  github: fongmanfong
  linkedin: fongjason23
  twitter: fongmanfong

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - CONTRIBUTING.md
  - LICENSE
